In [ ]:
# file สำหรับตรวจคำตอบ
# ในกรณีที่มีการสร้าง function อื่น ๆ ให้ระบุว่า input-output คืออะไรด้วย
'''
ชื่อ_รหัส(ex: ธนวัฒน์_6461)
1. ณพวิทย์ 6519
2. อนัญญา 6557
3.
'''

### Import Library

In [2]:
import roboticstoolbox as rtb
import numpy as np

from spatialmath import SE3
from math import pi

from HW3_utils import *
from FRA333_HW3_6519_6557 import *

### Question 1

In [3]:
#define link length
d1,a2, = 0.0892,-0.425

T_3_e = SE3(-0.39243,-0.093,0.109)*SE3(- 0.082,0,0)*SE3.RPY(0,-pi/2,0)

In [4]:
# Find MDH Parameter using Robotics toolbox
robot = rtb.DHRobot(
    [
        rtb.RevoluteMDH(d = d1, offset=pi),
        rtb.RevoluteMDH(alpha=pi/2),
        rtb.RevoluteMDH(a= a2)
    ],
    tool = T_3_e,
    name = "RobotHW3"
    )
print(robot)

DHRobot: RobotHW3, 3 joints (RRR), dynamics, modified DH parameters
┌────────┬───────┬────────────┬────────┐
│  aⱼ₋₁  │ ⍺ⱼ₋₁  │     θⱼ     │   dⱼ   │
├────────┼───────┼────────────┼────────┤
│    0.0 │  0.0° │  q1 + 180° │ 0.0892 │
│    0.0 │ 90.0° │         q2 │    0.0 │
│ -0.425 │  0.0° │         q3 │    0.0 │
└────────┴───────┴────────────┴────────┘

┌──────┬─────────────────────────────────────────────────┐
│ tool │ t = -0.47, -0.093, 0.11; rpy/xyz = 0°, -90°, 0° │
└──────┴─────────────────────────────────────────────────┘



### Question 1 Prove

In [5]:
# Random q
q = np.random.rand(3)*np.pi
print(f"Random q is : {q}")
# take jacobian fron the matrix above
J = robot.jacob0(q)

# Print it and compare with Jacobian matrix that you calculate 
J_e = endEffectorJacobianHW3(q)
print(f"Jacobian from calculate\n {J_e.round(6)}")
print("-----------------------------------")
print(f"Jacobian from prove\n {J.round(6)}")




# R,P,R_e,p_e = FKHW3(q)
# print(f"Position = {p_e}")
# print(f"Orientation =\n {R_e}")
# print(robot.fkine(q))

Random q is : [2.67977573 2.85832378 0.73394284]
Jacobian from calculate
 [[ 0.451642 -0.153604 -0.259946]
 [ 0.662806  0.076451  0.129379]
 [-0.        0.794614  0.386552]
 [ 0.       -0.445575 -0.445575]
 [ 0.       -0.895244 -0.895244]
 [ 1.        0.        0.      ]]
-----------------------------------
Jacobian from prove
 [[ 0.451642 -0.153604 -0.259946]
 [ 0.662806  0.076451  0.129379]
 [ 0.        0.794614  0.386552]
 [-0.       -0.445575 -0.445575]
 [-0.       -0.895244 -0.895244]
 [ 1.        0.        0.      ]]


### Question 2 Prove

In [6]:
# Random Q
q = np.random.rand(3)*np.pi
print(f"Random q : {q}")
# Check singularity from robotics toolbox
J = robot.jacob0(q)
# Get only 3x3 matrix determinant used only squared matrix
submatrix_J = J[0:3,:]
# Find determinant
determinant = np.linalg.det(submatrix_J)
prove_singular = abs(determinant) < 0.001
print(f"Determinant for proving : {determinant}")
print(f"ผลลัพธ์ที่ได้จาก Robotics toolbox : {prove_singular}")


#Check from calculate
prove_calculate = checkSingularityHW3(q)
print(f"ผลลัพธ์ที่ได้จากที่คำนวณ : {bool(prove_calculate)}")

#Compare prove_singular and prove_original is it the same
if (prove_calculate == prove_singular):
    print(f"ผลลัพธ์ทั้งสองมีค่าตรงกัน : {True}")
else :
    print (False)



Random q : [0.0365338  1.99253007 1.29476752]
Determinant for proving : -0.1289799454870287
ผลลัพธ์ที่ได้จาก Robotics toolbox : False
ผลลัพธ์ที่ได้จากที่คำนวณ : False
ผลลัพธ์ทั้งสองมีค่าตรงกัน : True


### Question 3 Prove


In [11]:
def proofeffort(q:list[float], w:list[float])->list[float] :
    
    # Get a tau from function computeEffortHW3(q,w)
    calculate_tau = computeEffortHW3(q,w)
    print(f"Calculate effort is {calculate_tau.round(6)}")

    # do a jacobian matrix using robotics toolbox
    J = robot.jacob0(q)
    subJ_T = np.transpose(J)
    tau_rtb = np.dot(subJ_T,w)
    print(f"RTB effort is {tau_rtb.flatten().round(6)}")
    # Compare 2 answer is it the same
    if np.allclose(tau_rtb,calculate_tau):
        return "The answer is the same"
    else :
        return "Wrong!"

# Random q and w
q = np.random.rand(3)*np.pi
w = np.random.uniform(0,np.pi, size = 6)
print (f"Random q is {q}")
print("------------------------------------------------------")
print(proofeffort(q,w))


Random q is [0.77665725 2.63697076 1.89892279]
------------------------------------------------------
Calculate effort is [1.193543 2.768885 2.109066]
RTB effort is [1.193543 2.768887 2.109068]
The answer is the same
