In [39]:
import roboticstoolbox as rtb
import numpy as np

from spatialmath import SE3
from math import pi

from HW3_utils import *
from FRA333_HW3_6519_6557 import *

คำถามข้อที่ 1

In [45]:
d1,a2, = 0.0892,-0.425
T_3_e = SE3(-0.39243,-0.093,0.109)*SE3(- 0.082,0,0)*SE3.RPY(0,-pi/2,0)
robot = rtb.DHRobot(
    [
        rtb.RevoluteMDH(d = d1, offset=pi),
        rtb.RevoluteMDH(alpha=pi/2),
        rtb.RevoluteMDH(a= a2)
    ],
    tool = T_3_e,
    name = "RobotHW3"
    )
print(robot)

q = np.random.rand(3)*np.pi
# q = [0, 0, 0]
J = robot.jacob0(q)
print(f"Jacobian from proof\n {J.round(6)}")
print("-----------------------------------")
J_e = endEffectorJacobianHW3(q)
print(f"Jacobian from original\n {J_e.round(6)}")

# R,P,R_e,p_e = FKHW3(q)
# print(f"Position = {p_e}")
# print(f"Orientation =\n {R_e}")
# print(robot.fkine(q))

DHRobot: RobotHW3, 3 joints (RRR), dynamics, modified DH parameters
┌────────┬───────┬────────────┬────────┐
│  aⱼ₋₁  │ ⍺ⱼ₋₁  │     θⱼ     │   dⱼ   │
├────────┼───────┼────────────┼────────┤
│    0.0 │  0.0° │  q1 + 180° │ 0.0892 │
│    0.0 │ 90.0° │         q2 │    0.0 │
│ -0.425 │  0.0° │         q3 │    0.0 │
└────────┴───────┴────────────┴────────┘

┌──────┬─────────────────────────────────────────────────┐
│ tool │ t = -0.47, -0.093, 0.11; rpy/xyz = 0°, -90°, 0° │
└──────┴─────────────────────────────────────────────────┘

Jacobian from proof
 [[ 0.118256  0.066145 -0.103319]
 [ 0.06908  -0.008086  0.01263 ]
 [-0.        0.08292   0.472121]
 [-0.       -0.121344 -0.121344]
 [-0.       -0.992611 -0.992611]
 [ 1.        0.        0.      ]]
-----------------------------------
Jacobian from original
 [[ 0.118256  0.066145 -0.103319]
 [ 0.06908  -0.008086  0.01263 ]
 [-0.        0.08292   0.472121]
 [ 0.       -0.121344 -0.121344]
 [ 0.       -0.992611 -0.992611]
 [ 1.        0.      

คำถามข้อที่ 2


In [55]:
q = np.random.rand(3)*np.pi
# Check singularity from robotics toolbox
J = robot.jacob0(q)
submatrix_J = J[0:3,:]
determinant = np.linalg.det(submatrix_J)
prove_singular = abs(determinant) < 0.001
print(f"Determinant for proving : {determinant}")
print(f"ผลลัพธ์ที่ได้จาก Robotics toolbox : {prove_singular}")



#Check from original
prove_original = checkSingularityHW3(q)
print(f"ผลลัพธ์ที่ได้จากที่คำนวณ : {bool(prove_original)}")

#Compare prove_singular and prove_original is it the same
if (prove_original == prove_singular):
    print(f"ผลลัพธ์ทั้งสองมีค่าตรงกัน : {True}")
else :
    print (False)



Determinant for proving : -0.1324448284553497
ผลลัพธ์ที่ได้จาก Robotics toolbox : False
ผลลัพธ์ที่ได้จากที่คำนวณ : False
ผลลัพธ์ทั้งสองมีค่าตรงกัน : True
